# fly.toml app configuration file generated for jupify-cron on 2024-10-22T04:20:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jupify-cron'
primary_region = 'ams'

[build]

[env]
  DOMAIN = 'https://jupify.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
