# fly.toml app configuration file generated for fupify on 2024-10-20T21:18:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jupify'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT='3000'
  HOST='0.0.0.0'
  DOMAIN='urbannovak.cc'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
